development:
  adapter: postgresql
  encoding: unicode
  database: burgermap_development
  pool: 5
  username: burgermap
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: burgermap_test
  pool: 5
  username: burgermap
  password: password1
